services:
  # --- ГОЛОВНИЙ СЕРВЕР ТА БАЗА ---
  server:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://yar4ik:${POSTGRES_PASSWORD}@db:5432/cinema?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=yar4ik
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=cinema
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yar4ik -d cinema" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  # --- REDIS (ЧЕРГА ПОВІДОМЛЕНЬ) ---
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  notifier-db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=yar4ik
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=cinema_notifier
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yar4ik -d cinema_notifier" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - notifier-db-data:/var/lib/postgresql/data

  notifier:
    build:
      context: ./notifier
    env_file:
      - .env
    environment:
      - MICROSERVICE_DATABASE_URL=postgresql://yar4ik:${POSTGRES_PASSWORD}@notifier-db:5432/cinema_notifier?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      notifier-db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  db-data:
  notifier-db-data: